### ISSUE TITLE
请去掉qiuniupkg.org 相关的包路径依赖

### ISSUE THREAD

**Issue by qiuchengw** [qiniu/x#16]
看起来 qiniupkg.org/x 代码已经改为github.com/qiniu/x 了，但是相关的包路径还没有改过来。
请更新下代码。

**Comment by leobuzhi** [comment]
把域名都改改成github的吧，不然某些项目管理软件上会遇到这个坑

**Comment by xushiwei** [comment]
内部有一个副本，导致这里没更新。计划后面统一内部外部。
