### ISSUE TITLE
go mod 拉取不到

### ISSUE THREAD

**Issue by iamxvbaba** [qiniu/x#19]
go get github.com/qiniu/x

go: finding github.com/qiniu/x/bytes.v7 v0.0.0-00010101000000-000000000000
go: github.com/qiniu/x/bytes.v7@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: error loading module requirements

**Comment by iamxvbaba** [comment]
只能本地 replace 了

**Comment by tangxinyao** [comment]
> 只能本地 replace 了

怎么replace？
