### ISSUE TITLE
go get获取包失败

### ISSUE THREAD

**Issue by cdddcw** [qiniu/x#20]
go get -v github.com/qiniu/x
Fetching https://qiniupkg.com/x/bytes.v7?go-get=1
Fetching https://qiniupkg.com/x/url.v7?go-get=1
Fetching https://qiniupkg.com/x/ctype.v7?go-get=1
Fetching https://qiniupkg.com/x/rpc.v7?go-get=1
Parsing meta tags from https://qiniupkg.com/x/bytes.v7?go-get=1 (status code 200)
Parsing meta tags from https://qiniupkg.com/x/ctype.v7?go-get=1 (status code 200)
get "qiniupkg.com/x/bytes.v7": found meta tag get.metaImport{Prefix:"qiniupkg.com/x", VCS:"git", RepoRoot:"https://github.com/qiniu/x"} at https://qiniupkg.com/x/bytes.v7?go-get=1
get "qiniupkg.com/x/bytes.v7": verifying non-authoritative meta tag

**Comment by xushiwei** [comment]
fixed
